language: php

dist: xenial

php:
  - 8.1
  - 8.2

services:
  - postgresql
  - mysql

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
env:
  jobs:
    - DB=mysql db_dsn='mysql://root@127.0.0.1/cakephp_test?init[]=SET sql_mode = "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"'
    - DB=pgsql db_dsn='postgres://postgres@127.0.0.1/cakephp_test'
    - DB=sqlite db_dsn='sqlite:///:memory:'
  global:
    - DEFAULT=1

jobs:
  allow_failures:
    - php: hhvm-nightly
  fast_finish: true
  include:
    - php: 8.1
      env: PHPCS=1 DEFAULT=0

    - php: 8.1
      env: PHPSTAN=1 DEFAULT=0

    - php: 8.1
      env: COVERAGE=1 DEFAULT=0 DB=mysql db_dsn='mysql://travis@0.0.0.0/cakephp_test'

before_script:
  - sh -c "composer install --no-interaction --dev"
  - if [[ $DB == 'mysql' ]]; then mysql -u root -e 'CREATE DATABASE cakephp_test;'; fi
  - if [[ $DB == 'pgsql' ]]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi
  - if [[ $PHPSTAN = 1 ]]; then composer stan-setup; fi

  - phpenv rehash
  - set +H

script:
  - if [[ $DEFAULT = 1 ]]; then composer test; fi
  - if [[ $COVERAGE = 1 ]]; then composer coverage-test; fi
  - if [[ $PHPCS = 1 ]]; then composer cs-check; fi
  - if [[ $PHPSTAN = 1 ]]; then composer stan; fi

after_success:
  - if [[ $COVERAGE = 1 ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
